#!/bin/bash

echo "======================================"
echo " VoxportCS VoIP Panel Installation"
echo "======================================"
echo ""
echo "✅ Installation completed successfully!"
echo ""
echo "🌐 Panel URL:"
echo "   http://$(hostname -I | awk '{print $1}')/"
echo ""
echo "🔐 Login:"
echo "   Username: admin"
echo "   Password: admin123"
echo ""
echo "📦 Services status:"
systemctl is-active nginx >/dev/null && echo "   ✔ Nginx running" || echo "   ✖ Nginx issue"
systemctl is-active voip-backend >/dev/null && echo "   ✔ Backend running" || echo "   ✖ Backend issue"
systemctl is-active mariadb >/dev/null && echo "   ✔ Database running" || echo "   ✖ Database issue"
systemctl is-active freeswitch >/dev/null && echo "   ✔ FreeSWITCH running" || echo "   ✖ FreeSWITCH issue"
echo ""
echo "🎉 VoxportCS is READY TO USE"
echo "======================================"
